baseurl = "https://www.brainvascular.com/" # Your main URL, used by search engines to index your site.
title = "BrainVascular - Information Source on Brain Vascular Health" # This title should contain relevant keywords related to your site's purpose.
theme = "newtheme" # The site's theme, helping to maintain consistency and structure, which is beneficial for SEO.
languageCode = "en-us" # Indicates the primary language of your site. Helps search engines to serve your site to appropriate language users.
defaultContentLanguage = "en" # Default content language. Helps with localized SEO if the theme provides `/i18n` directory for translations.

# You can enable comments with Disqus by adding your shortname.
#disqusShortname = "devcows"

# Enable Google Analytics for website analytics by adding your tracking code. This can help you understand your site's traffic sources and user behavior, which are useful for SEO.
googleAnalytics = ""

# Configure the length of the summary of post content. A good summary can improve click-through rates from search engine results pages.
summaryLength = 70 

# Number of posts displayed per page. This affects page loading speed, which is an important SEO factor.
paginate = 10 

# Default setting to not pluralize title pages. Singular page titles can often be more relevant to a user's specific search queries.
pluralizelisttitles = false 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This setting controls whether or not user-supplied Markdown can include HTML. If it's not necessary, it's safer and better for SEO to keep this as false.

[menu]
# Main menu configuration

# Keep in mind that each of these settings can help or hinder SEO. Make sure to use them thoughtfully, and regularly review your site's performance using tools like Google Analytics or Search Console.




[[menu.main]]
    name       = "Menu"
    identifier = "menu.features"
    url        = "/img/template-easy-customize.png"
    weight     = 3

[[menu.main]]
    name       = "Topics"
    identifier = "section.shortcodes"
    url        = ""
    weight     = 1
    parent     = "menu.features"
    post       = 1

[[menu.main]]
    name       = "Aneurysms"
    url        = "/topics/aneurysms"
    weight     = 1
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "Stroke"
    url        = "/topics/stroke"
    weight     = 1
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "Dural arteriovenous fistula"
    url        = "/topics/davf"
    weight     = 1
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "Arteriovenous malformation"
    url        = "/topics/avm"
    weight     = 1
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "Spinal vascular malformations"
    url        = "/topics/spinalvascular"
    weight     = 1
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "More information"
    identifier = "section.headervariations"
    url        = ""
    weight     = 2
    parent     = "menu.features"
    post       = 2

[[menu.main]]
    name       = "Editorial policy"
    url        = "/editorial-policy"
    weight     = 1
    parent     = "section.headervariations"

[[menu.main]]
    name       = "Further resources"
    url        = "/topics/links"
    weight     = 1
    parent     = "section.headervariations"



[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7


 

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Providing patient information on minimally invasive neurological therapies.</p>"
    copyright = "Copyright 2023. All rights reserved. This website is for informational purposes only and should not be used as a substitute for professional medical advice, diagnosis, or treatment."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = true
    logo_text = "brainvascular.com"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """
      """

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000



[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.mainlinks]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.




#[params.see_more]
#    enable = true
#    icon = "far fa-file-alt"
#    title = "Further questions?"
#    subtitle = "We welcome contact to answer further questions. "
#    link_url = "/contact"
#    link_text = "More info"



[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
